site_name: wt-wiki
nav:
    - Home: index.md
    - First: first.md
    - 开发工具使用: tools.md
    - Documents:
        - Usage: usage.md
        - Tutorial: tutorial.md
    - 编程:
        - Qt: Qt-Qml.md
        - Tutorial: tutorial.md
    - 视频课程: 
        - 马士兵: video/mashibing.md
theme:
  name: 'material'