site_name: wt-wiki
nav:
    - Home: index.md
    - First: first.md
    - IDE: tools.md
    - Documents:
        - Usage: usage.md
        - Tutorial: tutorial.md
    - 编程:
        - Qt: program/Qt-Qml.md
        - Python: program/python.md
        - Leetcode: program/Leetcode.md
        - Pyside2: program/pyside2.md
        - SQL: program/sql.md
        - SpringBoot: program/SpringBoot.md
        - Openlayers: program/openlayers.md
        - Postgre: program/Postgre.md
        - TensorFlow: program/TensorFlow.md
        - Vue: program/Vue.md
        - 编程规范: program/specification.md
    - 视频课程: 
        - 马士兵: video/mashibing.md
    - 办公: 
        - 电波模型: work/radio.md
theme:
  name: 'material'