site_name: wt-wiki
nav:
    - Home: index.md
    - First: first.md
    - 常用快捷键: tools.md
    - Documents:
        - Usage: usage.md
        - Tutorial: tutorial.md
    - 编程:
        - Qt: Qt-Qml.md
        - Tutorial: tutorial.md
theme:
  name: 'material'