site_name: wt-wiki
nav:
    - Home: index.md
    - First: first.md
    - IDE: tools.md
    - Documents:
        - Usage: usage.md
        - Tutorial: tutorial.md
    - 编程:
        - Qt: program/Qt-Qml.md
        - Python: program/python.md
        - Leetcode: program/Leetcode.md
        - Pyside2: program/pyside2.md
        - SQL: program/sql.md
    - 视频课程: 
        - 马士兵: video/mashibing.md
    - 办公: 
        - 电波模型: work/radio.md
theme:
  name: 'material'